version: '3'
services:
  app:
    build:
      context: ../.
      dockerfile: docker/development/Dockerfile
      args:
        RUBY_VERSION: "2.2"
    image: robertosilvino/railsgirls-dev-base:latest
    secrets:
      - secret_tst
    environment:
      - DB_DATABASENAME
      - RAILS_ENV
    command: "./docker/test_env.sh && vi"
secrets:
  secret_tst:
    file: ./secret_tst.txt